## numpy 函数示例
* [.all()与.any()](#1)
* [删除矩阵中的某些元素](#2)
* [np.where](#3)
* [生成随机数](#4)


###  <span id="1">.all()与.any()</span>
主要用于两个矩阵的比较  


In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3],
              [3, 6, 8]])
              
b = np.array([[2, 2, 3],
              [1, 3, 8]])
              
print(a == b)
print(a > b)
# .all()如果两个矩阵中的所有元素对应相等，则返回True，反之返回False
print((a == b).all())
# .any()如果判断两个矩阵中是否有相等的元素，有任何一个相等就行
print((a > b).any())

[[False  True  True]
 [False False  True]]
[[False False False]
 [ True  True False]]
False
True


###  <span id="2">删除矩阵中的某些元素</span>
```python
np.delete(numpy, index)
```
> * numpy - 需要删除的数组
> * index - 需要删除的元素的坐标


In [4]:
a = np.array([0, 1, 2, 4, 7])
# 删除4
print(np.delete(a, np.where(a == 4)))

[0 1 2 7]


###  <span id="3">np.where()</span>

返回满足条件的x坐标与y坐标数组

```
np.where(c[1:, 1:] == 1)
```
注意此时的x下标与y下标

In [11]:
c = np.array([[1, 0, 1],
              [0, 0, 1],
              [0, 0, 1]])

print(np.where(c ==1))

print(np.where(c[1:, 1:] == 1))

(array([0, 0, 1, 2], dtype=int64), array([0, 2, 2, 2], dtype=int64))
(array([0, 1], dtype=int64), array([1, 1], dtype=int64))


###  <span id="3">np.pad()</span>

常用与深度学习中的数据预处理，可以将numpy数组按指定的方法填充成指定的形状

```
pad(array, pad_width, mode, **kwargs)
```
> array——表示需要填充的数组
> pad_width——表示每个轴（axis）边缘需要填充的数值数目
参数输入方式为：（(before_1, after_1), … (before_N, after_N)），其中(before_1, after_1)表示第1轴两边缘分别填充before_1个和after_1个数值。取值为：{sequence, array_like, int}
> mode——表示填充的方式（取值：str字符串或用户提供的函数）,总共有11种填充模式
* 填充的方式：
> 1. "constant" ——表示连续填充相同的值，每个轴可以分别指定填充值，constant_values=（x, y）时前面用x填充，后面用y填充，缺省值填充0
> 2. "edge"——表示用边缘值填充
> 3. "linear_ramp"——表示用边缘递减的方式填充
> 4. "maximum, mean, median, minimum"分别用最大值、均值、中位数和最小值填充
> 5. "reflect" ——表示对称填充
> 6. "symmetric" ——表示对称填充
> 7. "wrap" ——表示用原数组后面的值填充前面，前面的值填充后面

#### 对一维数组的填充


#### 对多维数组的填充

In [33]:
# 对一维数组的填充
arr1D = np.array([1, 1, 2, 2, 3, 4])
print("origin:       " , arr1D)
print("constant:     " + str(np.pad(arr1D, (2, 3), 'constant', constant_values=2)))
print("edge:         " + str(np.pad(arr1D, (2, 3), 'edge')))
print("linear_ramp:  " + str(np.pad(arr1D, (2, 3), 'linear_ramp')))
print("maximum:      " + str(np.pad(arr1D, (2, 3), 'maximum')))
print("mean:         " + str(np.pad(arr1D, (2, 3), 'mean'))) 
print("median:       " + str(np.pad(arr1D, (2, 3), 'median')))
print("minimum:      " + str(np.pad(arr1D, (2, 3), 'minimum')))
print("reflect:      " + str(np.pad(arr1D, (2, 3), 'reflect')))
print("symmetric:    " + str(np.pad(arr1D, (2, 3), 'symmetric')))
print("wrap:         " + str(np.pad(arr1D, (2, 3), 'wrap')))

arr2D = np.array([[95, 96],
       [97, 98]])
print("origin:\n" , arr2D)
#在数组A的边缘填充constant_values指定的数值
#（3,2）表示在A的第[0]轴填充（二维数组中，0轴表示行），
# 即在0轴前面填充3个宽度的0，比如数组A中的95,96两个元素前面各填充了3个0；在后面填充2个0，比如数组A中的97,98两个元素后面各填充了2个0
#（2,3）表示在A的第[1]轴填充（二维数组中，1轴表示列），即在1轴前面填充2个宽度的0，后面填充3个宽度的0
print("constant:\n" + str(np.pad(arr2D,((3,2),(2,3)),'constant',constant_values = (-1,0))))
print("edge:\n" + str(np.pad(arr2D,((1,2),(2,1)),'edge')))
print("linear_ramp:\n" + str(np.pad(arr2D,((1,2),(2,1)),'linear_ramp')))
# #maximum填充模式还有其他控制参数，比如stat_length，详细见numpy库
print("maximum:\n" + str(np.pad(arr2D,((1,2),(2,1)),'maximum')))


origin:        [1 1 2 2 3 4]
constant:     [2 2 1 1 2 2 3 4 2 2 2]
edge:         [1 1 1 1 2 2 3 4 4 4 4]
linear_ramp:  [0 0 1 1 2 2 3 4 3 1 0]
maximum:      [4 4 1 1 2 2 3 4 4 4 4]
mean:         [2 2 1 1 2 2 3 4 2 2 2]
median:       [2 2 1 1 2 2 3 4 2 2 2]
minimum:      [1 1 1 1 2 2 3 4 1 1 1]
reflect:      [2 1 1 1 2 2 3 4 3 2 2]
symmetric:    [1 1 1 1 2 2 3 4 4 3 2]
wrap:         [3 4 1 1 2 2 3 4 1 1 2]
origin:
 [[95 96]
 [97 98]]
constant:
[[-1 -1 -1 -1  0  0  0]
 [-1 -1 -1 -1  0  0  0]
 [-1 -1 -1 -1  0  0  0]
 [-1 -1 95 96  0  0  0]
 [-1 -1 97 98  0  0  0]
 [-1 -1  0  0  0  0  0]
 [-1 -1  0  0  0  0  0]]
edge:
[[95 95 96 96]
 [95 95 96 96]
 [97 97 98 98]
 [97 97 98 98]]
linear_ramp:
[[ 0  0  0  0  0]
 [ 0 48 95 96  0]
 [ 0 48 97 98  0]
 [ 0 24 48 49  0]
 [ 0  0  0  0  0]]
maximum:
[[98 98 97 98 98]
 [96 96 95 96 96]
 [98 98 97 98 98]
 [98 98 97 98 98]
 [98 98 97 98 98]]



------
###  <span id="3">生成随机数</span>

* [numpy.random.rand](#3.1)  

* [numpy.random.randint(low, high=None, size=None, dtype='l')](#3.2)

* [numpy.random.uniform](#3.3) 

* [numpy.random.randn(d0, d1, ..., dn)(low=0.0, high=1.0, size=None)](#3.4)  

* [numpy.random.normal(loc=0.0, scale=1.0, size=None)](#3.5)

----
#### 参考
[https://www.cnblogs.com/sench/p/9683905.html](https://www.cnblogs.com/sench/p/9683905.html)


----

#### <span id="3.1">numpy.random.rand(d0, d1, d2,...dn)</span>

作用：产生一个给定形状的数组（其实应该是ndarray对象或者是一个单值），数组中的值服从[0,1)之间的均匀分布。

参数：d0, d, ..., dn : int，可选。如果没有参数则返回一个float型的随机数，该随机数服从[0, 1)之间的均匀分布。

返回值：ndarray对象或者一个float型的值

In [9]:
import numpy as np
# [0, 1]之间的随机数，指定形状（3行2列）
a = np.random.rand(3, 2)
print(a)
# 不指定形状
b = np.random.rand()
print(b)

[[0.23689509 0.84959009]
 [0.8801886  0.34142962]
 [0.09864728 0.50619271]]
0.352472171036615


####  <span id="3.2">numpy.random.randint(low, high=None, size=None, dtype='l')</span>

作用：返回一个在区间[low, high)中**离散均匀抽样**的数组，size指定形状，dtype指定数据类型。 
参数：  
low, high：int型，指定抽样区间[low, high)  

size：int型或int型的元组，指定形状  

dypte：可选参数，指定数据类型，比如int,int64等，默认是np.int  

返回值：如果指定了size，则返回一个int型的ndarray对象，否则返回一个服从该分布的int型随机数。

In [10]:
# 在[1, 10)之间离散均匀抽样，数组形状为3行2列
a = np.random.randint(1, 10, (3, 2))
print(a)
# 不提供size
b = np.random.randint(1, 10)
print(b)
# 指定dtype
c = np.random.randint(1, 10, dtype=np.int64)
print(c)
type(c)

[[1 9]
 [8 8]
 [7 4]]
8
4


numpy.int64

-----

####  <span id="3.3">numpy.random.uniform(low=0.0, high=1.0, size=None)</span>

作用：返回一个在区间[low, high)中**均匀分布**的数组，size指定形状。
参数：

low, high：float型或者float型的类数组对象。指定抽样区间为[low, high)，low的默认值为0.0，hign的默认值为1.0

size：int型或int型元组。指定形状，如果不提供size，则返回一个服从该分布的随机数。

In [6]:
# 在[1, 10)之间均匀抽样，数组形状为3行2列
a = np.random.uniform(1, 10, (3, 2))
print(a)
# 不提供size
b = np.random.uniform(1, 10)
print(b)
c = np.random.uniform()
print(c)

[[2.69776172 8.03639506]
 [7.33725799 5.73758045]
 [7.81415529 3.22647691]]
6.351476249470792
0.5052151775476945


#### <span id="3.4">numpy.random.randn(d0, d1, ..., dn)(low=0.0, high=1.0, size=None)</span>
作用：返回一个指定形状的数组，数组中的值服从**标准正态分布**（均值为0，方差为1）。  

参数：d0, d, ..., dn : int，可选。如果没有参数，则返回一个服从标准正态分布的float型随机数。  
 
返回值：ndarray对象或者float

In [7]:
# 3行2列
a = np.random.randn(3, 2)
print(a)
# 不提供形状
b = np.random.randn()
print(b)

[[-1.51935852  0.48431397]
 [ 0.39985805 -0.19728733]
 [ 0.50863094 -0.53478411]]
-0.6008487326204045


#### <span id="3.5">numpy.random.normal(loc=0.0, scale=1.0, size=None)
</span>

作用：返回一个由size指定形状的数组，数组中的值**服从 μ=loc,σ=scale 的正态分布**。  

参数：
loc : float型或者float型的类数组对象，指定均值 μ  

scale : float型或者float型的类数组对象，指定标准差 σ  

size : int型或者int型的元组，指定了数组的形状。如果不提供size，且loc和scale为标量（不是类数组对象），则返回一个服从该分布的随机数。  

输出：ndarray对象或者一个标量

In [8]:
# 标准正态分布，3行2列
a = np.random.normal(0, 1, (3, 2))
print(a)
# 均值为1，标准差为3
b = np.random.normal(1, 3)
print(b)

[[-0.63233601  0.43433585]
 [ 0.40547167  0.21032598]
 [-2.21205312  0.36268495]]
4.137566608686112
